# Generated by Django 4.0.4 on 2022-06-02 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='login',
            field=models.BooleanField(default='False', null=True),
        ),
    ]
