# Generated by Django 4.0.4 on 2022-05-30 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cita',
            old_name='id_mascota',
            new_name='id_usuario',
        ),
    ]
