# Generated by Django 4.0.4 on 2022-05-30 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_rename_id_mascota_cita_id_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='dia',
        ),
    ]
