# Generated by Django 4.0.4 on 2022-05-31 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_remove_cita_dia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='banco',
        ),
        migrations.RemoveField(
            model_name='datos_bancarios',
            name='id_banco',
        ),
        migrations.AddField(
            model_name='datos_bancarios',
            name='banco',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
