# Generated by Django 4.0.4 on 2022-05-31 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_delete_banco_remove_datos_bancarios_id_banco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_bancarios',
            name='num_tarjeta',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
    ]
